### ISSUE TITLE
Feature request: Add emacs and/or vim integration for editing content translation

### ISSUE THREAD

**Issue by OrionRandD** [postiffm/bibledit-desktop#106]
It would be great if there was a feature to integrate emacs and/or vim for speeding up the translation work, especially from Greek/Hebrew to other languages.
I am dreaming?

**Comment by postiffm** [comment]
We won't be integrating vim or emacs editors. We are working on a new USFM editor.

**Comment by OrionRandD** [comment]
On Tue, Apr 23, 2019 at 01:45:24PM -0700, Matt Postiff wrote:
> We won't be integrating vim or emacs editors. We are working on a new USFM editor.

Why not? They have wonderful features that can speed up the workflow translation...
Specially the vimkeybindgs.
Any reason for not implementing this feature? And they are also opensource projects....
