### ISSUE TITLE
[gtk3] Use GtkApplication

### ISSUE THREAD

**Issue by rluzynski** [postiffm/bibledit-desktop#115]
We should use ```GtkApplication``` once we port to gtk3. One of the features of ```GtkApplication``` is ensuring that only one instance of the application is running on one desktop. This feature can be easily turned off by tweaking the GNOME system options and may not work on other systems so the recent work on the issue #1 is still relevant and required. Another feature is a better integration with GNOME and managing the app menu.

@postiffm, what is the preferred globally-unique application ID for Bibledit Desktop?

Links:

* https://wiki.gnome.org/HowDoI/GtkApplication
* https://developer.gnome.org/gtk3/stable/GtkApplication.html
* https://python-gtk-3-tutorial.readthedocs.io/en/latest/application.html
* https://stackoverflow.com/questions/41892302/what-is-the-preferred-way-to-write-gtk-applications
* however note that GNOME has recently recognized the app menu (but not ```GtkApplication```) as deprecated: https://gitlab.gnome.org/GNOME/Initiatives/wikis/App-Menu-Retirement

**Comment by postiffm** [comment]
If we change to GtkApplication, will that break Bibledit-Desktop on Windows (built on top of msys2)?

I am unsure about the globally-unique application ID.

We do have to handle command-line arguments (most importantly, --debug, but there are a couple of others, and in the future there will be more).

**Comment by postiffm** [comment]
OK, I understand it better now. I think the globally-unique application ID should be org.bibleditdesktop. 

It should NOT be bibledit-gtk.desktop. GTK just causes confusion among end users, and they don't care what library is used to implement the GUI. 

bibledit-desktop.desktop is a bit redundant sounding. The point of the name "bibledit-desktop" is that we run on a desktop and laptop computers without needing the cloud or the web (bibledit-cloud or bibledit-web). Our users are in places where Internet access is scarce. So I decided to use Bibledit-desktop to indicate that, and to get rid of the -gtk suffix.

The website is http://bibleditdesktop.org. Eventually that website may have its own space on the Internet.

**Comment by LAfricain** [comment]
>bibledit-desktop.desktop is a bit redundant sounding.

Yes but no body see the second "desktop" :)

**Comment by postiffm** [comment]
Good point :-)

**Comment by postiffm** [comment]
I believe this issue is completed now.
