### ISSUE TITLE
click on the crossreferences in the reference windows doesn't work with the new release

### ISSUE THREAD

**Issue by LAfricain** [postiffm/bibledit-desktop#130]
With the new release, if I use Check → result in the references windows, and if I click on the link to the crossreference I have this answer: `The URL can’t be shown`
I think this is related to the localisation. Because in the Concordance windows the links for the crossreferences are displayed in English in my French system and it's working.
This a critical issue, because I can work well....

**Comment by postiffm** [comment]
Let me see if I can understand the problem first.

**Comment by LAfricain** [comment]
OK

**Comment by postiffm** [comment]
For some reason the links that are constructed are of the form "goto 0" or "goto 1"

**Comment by postiffm** [comment]
Fixed in 5009280

**Comment by postiffm** [comment]
The same bug was present in show related verses and check key terms. Fixed in 839f0ca
