### ISSUE TITLE
New po file for localisation

### ISSUE THREAD

**Issue by LAfricain** [postiffm/bibledit-desktop#16]
It can be very nice to have a new .po file for localisation. The actually the po file doesn't have all the string to be translate. Maybe using launchpad can help.

**Comment by LAfricain** [comment]
Exemple the file templates/gtkbuilder.referencesettingsdialog.xml and doc/sites.xml (for example). If need I can add the place with lake of localization.

**Comment by postiffm** [comment]
src/dialogbook.cpp:123 is done with the latest commit.

**Comment by postiffm** [comment]
doc/site.xml is a huge project to translate!

**Comment by postiffm** [comment]
By "lake of localization" I think you mean "lack of localization." Any pointers you want to give to line numbers will be helpful.

**Comment by postiffm** [comment]
Regarding src/windowreferences.cpp, I think that is mostly localized. There are strings for DEBUG calls that don't need localization, and there are strings inside of sql database commands that I don't think can be localized. At least I'm not confident that they can be localized since they refer to pre-existing table/column identifiers.

**Comment by postiffm** [comment]
src/windowreferences.cpp did have some strings that I missed. These are fixed in the latest commit.

The template\gtkbuilder*.xml files are going to be a little more complicated. They are important, as Cyrille points out.

**Comment by postiffm** [comment]
Cyrille, I am going to upgrade the bibledit-desktop package to a modern gettext method of building so that we can more easily extract strings from the gtkbuilder files. These have to be handled specially because the translations have to be merged back into the xml file after the translator (you) makes the translation. This will be a bit more pain initially, but much better in the long run. 

Thank you for your help on all this, and patience!

**Comment by LAfricain** [comment]
Le 13/05/2017 à 21:54, Matt Postiff a écrit :
>
> By "lake of localization" I think you mean "lack of localization." Any 
> pointers you want to give to line numbers will be helpful.
>
Yes lack and not lake... Ok for the line numbers. But if you want I can 
do the job of verification. and correct the line with the code _() and 
send you the modified files?

**Comment by LAfricain** [comment]
mainwindows.cpp: 469

Now I understood how to use git, I could update my local git from bibledit-desktop. Easier to update when I want to verify my translation.

**Comment by postiffm** [comment]
mainwindows.cpp: 469 is fixed and now in the repository.
I welcome your help on other strings in the src\.cpp files. However, we cannot mark the strings the same way in templates\gtkbuilder files. This is why I am updating how strings are internationalized in bibledit-desktop, so that this problem will be solved automatically--once all the changes are made to the build system.

**Comment by LAfricain** [comment]
Ok I will continue to find it. Ok pour the template/gtkbuilder, I will 
be patient...

**Comment by LAfricain** [comment]
src/windowstyles.cpp:45
src/windowtabbed.cpp:185
src/usfmtools.cpp:729
src/outline.cpp:174
src/mainwindow.cpp:5447
shutdown/bibledit-shutdown.cpp:99
src/reporting.cpp:453:  cout << "Status for chapter " << chapter << endl;
src/reporting.cpp:765:  HtmlWriter htmlwriter("Status Report", false, false, true);
src/reporting.cpp:766:  htmlwriter.heading(1, "Status Report " + project);
src/dialogimportnotes.cpp:337:        category_element = "Status";

In this picture you can the english word but I couldn't find it with grep?? For this reason I send you a picture.
![system_log_window](https://cloud.githubusercontent.com/assets/19690477/26033748/94b21d4e-38a9-11e7-92e1-461a3ee4ecc2.png)
And in the menu Preferences Project notes:
![project_notes](https://cloud.githubusercontent.com/assets/19690477/26033758/f2834bdc-38a9-11e7-81cc-883d20a82c33.png)

src/password.cpp:54
src/dialogtextreplacement.cpp:114
src/scripts.cpp:31
src/dialogcheck.cpp:550
I know for the gtkbuilder, but I give you nevertheless : 
templates/gtkbuilder.guidialog.xml
gtkbuilder.planningsetupdialog.xml
templates/gtkbuilder.gotoreferencedialog.xml
templates/gtkbuilder.bulkspellingdialog.xml
templates/gtkbuilder.showprojectnotesdialog.xml

**Comment by LAfricain** [comment]
src/export_utils.cpp:665:    spawn.progress("Compiling", false);

**Comment by postiffm** [comment]
src/mainwindow.cpp:5447
          Generally I don't put debugging information in translation,
      but I suppose we can.
    
    src/dialogimportnotes.cpp:337: category_element = "Status"; 
        I am not sure if we can translate these.
    
    Project notes:
        categories.push_back(_("No issue"));
        categories.push_back(_("For myself"));
        categories.push_back(_("For subteam"));
        categories.push_back(_("For team"));
        categories.push_back(_("For scholar"));
        categories.push_back(_("For panel"));
        categories.push_back(_("For church"));
        categories.push_back(_("For consultant"));
        categories.push_back(_("For Bible society"));
    So these are already marked. Not sure why they were not translated
    yet. Did you not see them in the .po file? Maybe they are not in
    there yet because of something wrong that I did?
    
    I think the system log window English is generated by an xml parser
    somewhere, but not in our source code...
        
    All other changes you suggested in this email are done in my repo,
    except for gtkbuilder files. I am going to get to those soon. I also
    marked a number of other strings that I missed before.
    
    Matt
    
    On 5/14/2017 9:05 AM, LAfricain wrote:
    
    
      src/windowstyles.cpp:45
        src/windowtabbed.cpp:185
        src/usfmtools.cpp:729
        src/outline.cpp:174
        src/mainwindow.cpp:5447
        shutdown/bibledit-shutdown.cpp:99
        src/reporting.cpp:453: cout << "Status for chapter "
        << chapter << endl;
        src/reporting.cpp:765: HtmlWriter htmlwriter("Status Report",
        false, false, true);
        src/reporting.cpp:766: htmlwriter.heading(1, "Status Report " +
        project);
        src/dialogimportnotes.cpp:337: category_element = "Status";
      In this picture you can the english word but I couldn't find it
        with grep?? For this reason I send you a picture.
        
        And in the menu Preferences Project notes:
        
      src/password.cpp:54
        src/dialogtextreplacement.cpp:114
        src/scripts.cpp:31
        src/dialogcheck.cpp:550
        I know for the gtkbuilder, but I give you nevertheless :
        templates/gtkbuilder.guidialog.xml
        gtkbuilder.planningsetupdialog.xml
        templates/gtkbuilder.gotoreferencedialog.xml
        templates/gtkbuilder.bulkspellingdialog.xml
        templates/gtkbuilder.showprojectnotesdialog.xml
      —
        You are receiving this because you commented.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/postiffm/bibledit-desktop","title":"postiffm/bibledit-desktop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/postiffm/bibledit-desktop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LAfricain in #16: src/windowstyles.cpp:45\r\nsrc/windowtabbed.cpp:185\r\nsrc/usfmtools.cpp:729\r\nsrc/outline.cpp:174\r\nsrc/mainwindow.cpp:5447\r\nshutdown/bibledit-shutdown.cpp:99\r\nsrc/reporting.cpp:453:  cout \u003c\u003c \"Status for chapter \" \u003c\u003c chapter \u003c\u003c endl;\r\nsrc/reporting.cpp:765:  HtmlWriter htmlwriter(\"Status Report\", false, false, true);\r\nsrc/reporting.cpp:766:  htmlwriter.heading(1, \"Status Report \" + project);\r\nsrc/dialogimportnotes.cpp:337:        category_element = \"Status\";\r\n\r\nIn this picture you can the english word but I couldn't find it with grep?? For this reason I send you a picture.\r\n![system_log_window](https://cloud.githubusercontent.com/assets/19690477/26033748/94b21d4e-38a9-11e7-92e1-461a3ee4ecc2.png)\r\nAnd in the menu Preferences Project notes:\r\n![project_notes](https://cloud.githubusercontent.com/assets/19690477/26033758/f2834bdc-38a9-11e7-81cc-883d20a82c33.png)\r\n\r\nsrc/password.cpp:54\r\nsrc/dialogtextreplacement.cpp:114\r\nsrc/scripts.cpp:31\r\nsrc/dialogcheck.cpp:550\r\nI know for the gtkbuilder, but I give you nevertheless : \r\ntemplates/gtkbuilder.guidialog.xml\r\ngtkbuilder.planningsetupdialog.xml\r\ntemplates/gtkbuilder.gotoreferencedialog.xml\r\ntemplates/gtkbuilder.bulkspellingdialog.xml\r\ntemplates/gtkbuilder.showprojectnotesdialog.xml"}],"action":{"name":"View Issue","url":"https://github.com/postiffm/bibledit-desktop/issues/16#issuecomment-301311469"}}}

**Comment by LAfricain** [comment]
Le 16/05/2017 à 04:00, Matt Postiff a écrit :
>
> src/mainwindow.cpp:5447
>     Generally I don't put debugging information in translation,
> but I suppose we can.
I can be really interresting...
>
> src/dialogimportnotes.cpp:337: category_element = "Status";
>     I am not sure if we can translate these.
Me too, but if it is between ""  I think so??
>
> Project notes:
>     categories.push_back(_("No issue"));
>     categories.push_back(_("For myself"));
>     categories.push_back(_("For subteam"));
>     categories.push_back(_("For team"));
>     categories.push_back(_("For scholar"));
>     categories.push_back(_("For panel"));
>     categories.push_back(_("For church"));
>     categories.push_back(_("For consultant"));
>     categories.push_back(_("For Bible society"));
> So these are already marked. Not sure why they were not translated
> yet. Did you not see them in the .po file? Maybe they are not in
> there yet because of something wrong that I did?
Yes it is : I add
src/notes_utils.cpp:635:    categories.push_back(_("For myself")); in 
the po file...

>
> I think the system log window English is generated by an xml parser
> somewhere, but not in our source code...
>
OK
> All other changes you suggested in this email are done in my repo,
> except for gtkbuilder files. I am going to get to those soon. I also
> marked a number of other strings that I missed before.
Ok I can pull it to my local.... And after compiling it again I'll come 
back with the new (or not :)) strings...

**Comment by postiffm** [comment]
Cyrille, please merge in the latest commit to master in to your working copy and check out the bibledit.pot and the new fr.po. I have manually put together those files and as a result have at least 120 more strings found in gtkbuilder.*.xml files. Some of them are duplicates of ones you have already translated, but many are new. If you can put in the translations and then create a new, separate pull request, that would be great. Thanks.

**Comment by LAfricain** [comment]
Ok I did the merge, but I had some probleme  with it, now it's okay. I
would to do a pull request again just for this commit: Correction of a
lot of errors I did during the previous corrections

But I did it for all the commit!!! I'm sorry, I didn't found the
solution to do just for one commit on my fork?? If you can give me the
solution.
I found too the solution for make check of my  addition before commit
it. Now I would work better.
A proposition is to add some page from
https://sites.google.com/site/bibledit/home to the local help. If you
agree with I'll do it. After we can reflect how to translate it...

**Comment by LAfricain** [comment]
I sorry still...
It seems to be okay about the pull request?? Can you confirm that it's
just the commit about "Correction of a lot of errors I did during the
previous corrections" that i did?
