### ISSUE TITLE
Conflict with the bibledit.xpm picture on Ubuntu

### ISSUE THREAD

**Issue by LAfricain** [postiffm/bibledit-desktop#19]
When installing the two apps (bibledit and Bibledit-desktop) with a deb (created with checkinstall for BB-desktop). I have a conflict with the  bibledit.xpm picture.
It needs to be renamed.

**Comment by postiffm** [comment]
Your pull request looks fine to solve this. I'll get to it tomorrow, I think.

**Comment by postiffm** [comment]
This is integrated now.
