### ISSUE TITLE
Notes are not saved

### ISSUE THREAD

**Issue by LAfricain** [postiffm/bibledit-desktop#26]
If I add a note (Project notes > new), the next time I use bibledit-gtk, it is no more present. I can't find the notes???

**Comment by LAfricain** [comment]
I can't explain why but today it seems to be OKAY. I can display all the note created and the date is OKAY too.
 I noticed too that some times the reference display in English and some times in French.

**Comment by postiffm** [comment]
Have you had this problem lately? I believe I fixed a longstanding bug some time ago that is related to this issue.

**Comment by LAfricain** [comment]
Let me see :)

**Comment by LAfricain** [comment]
Seems to be okay I close it, if I encounter the problem again I will reopen it.
