### ISSUE TITLE
Windows closed on a previous session open again to the new

### ISSUE THREAD

**Issue by LAfricain** [postiffm/bibledit-desktop#33]
If I close the windows on a session, for instance, the windows stylesheet, note and outline, it wil open again  to the next session! See this capture:
![all_windows_open](https://cloud.githubusercontent.com/assets/19690477/26725019/422cba1c-4794-11e7-906b-c8e59d20dd18.png)

**Comment by postiffm** [comment]
This doesn't happen for me. I think maybe an i18n problem with a config filename or something like that.On Jun 2, 2017 8:07 AM, LAfricain <notifications@github.com> wrote:If I close the windows on a session, for instance, the windows stylesheet, note and outline, it wil open again  to the next session! See this capture:

**Comment by LAfricain** [comment]
I use the english gui, the same problem, maybe I need to do a new package?
If it can help, the content of th system log during opening:
T1000692352 WIN32 was NOT defined in this build
T1000692352 Command-line option --debug=0
T1000692352 List of directories and other paths we know about:
T1000692352 Run directory:     .
T1000692352 Executable name:     bibledit-desktop
T1000692352 Package data:     /usr/share/bibledit-desktop
T1000692352 Home:     /home/cyrille
T1000692352 Root:     /home/cyrille/.bibledit
T1000692352 Projects:     /home/cyrille/.bibledit/projects
T1000692352 Notes:     /home/cyrille/.bibledit/notes
T1000692352 Stylesheets:     /home/cyrille/.bibledit/stylesheets
T1000692352 Configuration:     /home/cyrille/.bibledit/configuration
T1000692352 Pictures:     /home/cyrille/.bibledit/pictures
T1000692352 Resources:     /home/cyrille/.bibledit/resources
T1000692352 Scripts:     /home/cyrille/.bibledit/scripts
T1000692352 User templates:     /home/cyrille/.bibledit/templates
T1000692352 Temp:     /tmp/bibledit
T1000692352 Templates:     /tmp/bibledit/templates
T1000692352 Restore:     /home/cyrille/.bibledit.restored
T1000692352 Path:    
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
T1000692352 Copy util:     cp
T1000692352 Copy recursive:     cp -r
T1000692352 Move util:       mv -f
T1000692352 Remove util:     rm
T1000692352 Rmdir util:      rm -rf
T1000692352 Mkdir:           mkdir -p
T1000692352 Diff util:       diff
T1000692352 Tar util:        tar
T1000692352 Zip util:        zip
T1000692352 Unzip util:      unzip.exe
T1000692352 gzip util:       gzip
T1000692352 pdfviewer:       evince
T1000692352 Any of these that are blank indicate that we have not worked
on them yet!!!!!
T1000692352 Git:            
T1000692352 bibledit_git    
T1000692352 Curl util:      
T1000692352 gobiblecreator:   
T1000692352 bibledit_shutdown:   
T1000692352 php-cli:         
T1000692352 texlive-xetex:   
T1000692352 teckit_compile:   
T1000692352 head:            
T1000692352 touch:           
T1000692352 osis2mod:        
T1000692352 cmdshell:        
T1000692352 tasklist:        
T1000692352 merge:           
T1000692352 bwoutpost:        ./bwoutpost.exe
T1000692352 Finished booklocalizations
T1000692352 Finished URLTransport
T1000692352 Checked for --xembed
T1000692352 Finished upgrade
T1000692352 Set up window icon fallback
T1000692352 Finished initialization...running gtk_main
T1000692352 Webserver Access: ok
T1000692352 Creating Stylesheet called 'Standard'
T1000692352 Command: cp /usr/share/bibledit-desktop/stylesheet.xml
/home/cyrille/.bibledit/stylesheets/.xml2
T1000692352 Creating Stylesheet called ''
Entity: line 534: parser error : Opening and ending tag mismatch: book
line 417 and bibledit-localized-books
</bibledit-localized-books>

**Comment by LAfricain** [comment]
I don't know why, but with the lasts commit this problem disappears.

**Comment by postiffm** [comment]
I am unclear now what the problem was: 
1) upon restarting bibledit-desktop, the windows opened last time DO open?
2) upon restarting bibledit-desktop, the windows opened last time DO NOT open?
There was a fix I made some time ago to fix some windows like the analysis window so that if it was open before shutdown, it would open automatically again on start-up of bibledit.

By the way, have you looked at the Analysis and concordance windows?

**Comment by LAfricain** [comment]
It is the opposite:
upon restarting bibledit-desktop, the windows **CLOSED** last time DO open. Now no more, I tested with all windows.

**Comment by LAfricain** [comment]
The problem is still present. It seems BB doesn't remember the last windows configuration, when closing:
![windows_when_closing_bb](https://user-images.githubusercontent.com/19690477/58313785-a8e91400-7e0e-11e9-8455-7472861ff1b1.png)

When reopening:
![window_when_reopen](https://user-images.githubusercontent.com/19690477/58313849-cb7b2d00-7e0e-11e9-9b0b-af46002f4e53.png)


I noticed also the missing close button with some windows:
![no_cross](https://user-images.githubusercontent.com/19690477/58313642-590a4d00-7e0e-11e9-8113-178601e4f5bc.png)

**Comment by LAfricain** [comment]
I found a work around.
Rename the .bibledit folder. Copy all the project and the files needed. Reopen BB-Desktop.
