### ISSUE TITLE
The names of bible books don't display after lasts commits

### ISSUE THREAD

**Issue by LAfricain** [postiffm/bibledit-desktop#36]
After the lasts commits the book names doesn't display well in French.
I have no more idea... I use the former version of Bibledit-desktop. The commit https://github.com/postiffm/bibledit-desktop/commit/9b18a7f72d923a79ec16cb3c623d08f2adb85582

**Comment by postiffm** [comment]
Is this only in French, or also in English?

**Comment by LAfricain** [comment]
If think just in French. I use the old release. Happy to see you again :)

**Comment by postiffm** [comment]
Sorry I have been absent! I have a new Linux build environment in a VirtualBox virtual machine running on Windows. It is helpful. I'm also trying out KDevelop integrated development environment.

**Comment by LAfricain** [comment]
Thursday I'll go to Kinshasa to install bb-desktop to Verbum Bible :)

**Comment by postiffm** [comment]
LAfricain, I think this is because I changed only one direction books_id_to_english became books_id_to_localname. I need to fix the other direction, so that books_english_to_id will become books_localname_to_id

**Comment by postiffm** [comment]
Hi again, try the latest commit, dd6ac73, I *think* it should handle the Bible book names better. Please let me know what you find. It is hard for me to test this properly.

**Comment by LAfricain** [comment]
Happy to see you again! Okay I'll found time to test...

Il 14/02/2018 04:56, Matt Postiff ha scritto:

**Comment by LAfricain** [comment]
It seems to work! I run a check for test, and the names of books seems to be in French (it runs quickly for this I say "seems").

**Comment by LAfricain** [comment]
I have a question what's the need of the language_code_language.xml files? Because if I change it, it doesn't affect the transalation of the bible names in the gui.

**Comment by LAfricain** [comment]
I'm sorry, but now it displays well but if I stay with the  book names translated in the fr.po file, When I run the check for chapters and verses, it gives me all the verses as bad...
Workaround is actually to not translate the book names, and it runs ok. 
![chapters](https://user-images.githubusercontent.com/19690477/36255969-4b7d04e0-1251-11e8-877b-79fd21ce65b4.png)

It's already better because we can use the software, then before not.

**Comment by postiffm** [comment]
Can you please explain more? What check are you running? Please show an example of the actual result, alongside of the result you expect. Thanks.

**Comment by LAfricain** [comment]
The check is in the menu `Checks > Chapters and verses` then you choose the books to check, if I check  with the books not translated (the books are displayed during the checks work) in the po the results are correct, see the capture:
![check_genesis](https://user-images.githubusercontent.com/19690477/36310027-0c459914-1327-11e8-9845-ea6404a97e7a.png)

You can see just 4 errors. Then if I use the po with the strings of the book's names translated it will consider all the verse as an error, as you can see on the picture of the second message.

**Comment by LAfricain** [comment]
maybe on Ubuntu you can install lightdm-gtk-greteer, (it gives possibility to choose the language at login) and the french language pack, after that you can try yourself (if you want). If you need usfm file for test, you can download it to my [gitlab](https://gitlab.com/lafricain79/konvb) repo.

**Comment by postiffm** [comment]
To run in French on my English system, here is what I did: Installed the language pack on Ubuntu, then ran the script bibledit-desktop/linux/bibledit-fr.sh. Basically, this is all it does:
export LANG=fr_FR.UTF-8
export LANGUAGE=fr_FR:fr
then run /usr/bin/bibledit-desktop

And I do see the problem. Strange...now to debug it...

**Comment by postiffm** [comment]
I notice that you use «» as quotation marks many times, but sometimes smart double quotation marks ". Is there a difference? The concordance needs to know about these to do its job properly.

**Comment by LAfricain** [comment]
> «» as quotation marks many times, but sometimes smart double quotation marks ". Is there a difference?

The «» is the normal french punctuation with non break space before or after it. Where did you notice the "? tI may be a mistake, but it is possible to use it also in French.
Or your question is about an usfm text? Then we use the «» for the first sentence, and if we have an another quotation in the first then we use the “” (not the ", in French it not the same :) )

**Comment by postiffm** [comment]
Here are some double quotation marks:
Items 1 - 8 of 8 [actions]

Joshua 5:12 " Na kilumbu landaka, manna* vandaka diaka ve, sambu na bana ya Israel, bo vandaka kudia bima ya bilanga ya bo kunaka na ntoto yina. Na mvula yina Manna vandaka diaka ve sambu na bana ya Israel;- bo diaka bima ya ntoto ya Kanana butilaka bo.

2 Samuel 23:38 Ira, muntu ya Yatir. " Gareb, muntu ya Yatir.

Psalms 58:1 Yo me katuka na mukanda ya mfumu ya bayina ke yimbaka. "Kubebisa ve " Nkunga ya Davidi, na ndinga ya nsi-nsi.

Psalms 59:1 Yo me katuka na mukanda ya mfumu ya bayina ke yimbaka. "Kubebisa ve " Nkunga ya Davidi, na ndinga ya nsi-nsi, ntangu Saül tindaka bantu na kukengila nzo na yandi sambu na kufwa yandi. Davidi tubaka nde :

Psalms 60:1 Yo me katuka na mukanda ya mfumu ya bayina ke yimbaka. Nkunga ya " kintuntu ya nseke mosi kele nsiku". Nkunga ya Davidi, na ndinga ya nsi-nsi,

Luke 6:11 Kansi bo yonso dasukaka ; bo yantikaka kutubana bo na bo nde : « Nki beto lenda sala na Yezu ? »

Luke 9:12 Kwa ntangu yantikaka kudinda, bantumwa yonso kumi na zole finamaka na Yezu ; bo nde : « Tubila bantu bo vutuka. Bo kwenda kulala na babwala ti na tu-babwala ya fioti ikele na nziunga. Kuna bo sosa mpi madia, sambu kwaku beto kele na nseke. »

Luke 22:38 N Balongoki tubilaka Yezu nde : B "Mfumu, tala ! Beto kele na bambele zole. " N Kansi Yezu vutulaka nde : + « Bika mambu yai. »

You can use Ctrl+F to search for " and it should show you some examples.

Also, there are some other strange words or characters that you can see if you create a new concordance.

**Comment by LAfricain** [comment]
Hello,
I don't understand well about concordance? Did you test it with an other language? My problem is not about concordance, I haven't use it yet. My problem is about checks of chapters and verses. If the names of the books are translated into the fr.po file. The checks don't run well, as I described it upper.

About the usfm files, the punctuation are not yet checked in the OT, just in the new. Some issues can still be in the footnotes in the NT.
For Luc 22,38 it is an issue it should be «»

**Comment by postiffm** [comment]
OK. I'm debugging on your issue. First thing I had to do was to to go File | Project | Properties and change the language to French and the versification to something, maybe Roman Catholic 2. Do those match your settings?

**Comment by postiffm** [comment]
Can you show the contents of .bibledit/projects/KONVB/data/ ?
I think the problem is that the Bible book names are stored there in English. They should be stored in French...

**Comment by postiffm** [comment]
When I deleted the project and imported again...in French mode...the file names in .bibledit/projects/konvb/data were in French. Then things started working better. Here is the check of chapters and verses:

Éléments 1 - 25 de 7979 [suivant] [actions]

Genèse 48:21 [Il n'y a pas suffisamment de verset dans le chapitre] Na nima, Israel tubaka na Yozefo nde: « Mono ke fwa, kansi Nzambi ta vanda na beno, yandi ta vutula beno na ntoto ya batata na beno.» Sambu na mono ntoto ya Sikem ya mono botulaka na ba-Amori na mvita, mono ta pesa nge yo. Dikabu na nge ta vanda ya kuluta yina ya bampangi na nge.

Exode 7:23 [Interruption dans la versification après le verset 21] Faraon vutukaka na nzo na yandi, yandi talaka yonso yina mpamba.

Exode 11:6 [Interruption dans la versification après le verset 4] Bidilu ya ngolo ya bo me waka ntete ve, ya bo ta waka mpi ve, ata vanda na Ezipiti ya mvimba.

Exode 20:11 [Interruption dans la versification après le verset 9] Sambu Mfumu Nzambi gangaka zulu ti ntoto, nzadi ti yina yonso kele na kati. Kansi na kilumbu ya nsambwadi yandi me pema. Yo yina, Mfumu Nzambi sambulaka kilumbu ya nsambwadi, yo kumaka kilumbu na yandi.

Exode 21:18 [Interruption dans la versification après le verset 16] « Kana bantu kuswana, mosi kulwadisa yina yankaka na ditadi to na kubula yandi dikofi, kana muntu yina ya bo me bula kufwa ve, kansi yandi bikala na mbeto, kana yandi lenda telama ti kubasika na nganda na nsadisa ya nti ya kutambudila,

Lévitique 12:3 [Interruption dans la versification après le verset 1] Na kilumbu ya nana, bo ta yotisa mwana.

Lévitique 14:57 [Interruption dans la versification après le verset 55] Yo ke songa nki bo fwete kusala na yina kele ya gedila ve ti yina kele ya gedila. Yai bansiku me tadila maladi ya wazi.

Lévitique 27:13 [Interruption dans la versification après le verset 11] Kansi kana bo zola kusumba yo diaka, bo ta yika na zulu ndambu mosi ya tanu ya ntalu ya mbongo yina.

Nombres 36:8 [Interruption dans la versification après le verset 6] Konso mwana-nkento yina kele ti dikabu ya ntoto na kati ya kikanda mosi ya makanda ya bana ya Israel, yandi fwete bala bakala kaka na kikanda mosi ya tata na yandi. Mpila yina, konso mwana ya Israel ta baka dikabu ya ntoto na ntoto ya batata na yandi.

Deutéronome 8:20 [Interruption dans la versification après le verset 18] Mutindu Mfumu Nzambi fwaka bansi yina ya vandaka na ntwala na nge, yandi ta fwa nge mpi kiteso mosi sambu nge me wa ve ndinga ya Mfumu Nzambi, Nzambi na nge.

Juges 3:3 [Interruption dans la versification après le verset 1] bamfumu tanu ya ba-Filisti, bantu yonso ya Kanana, bantu ya kimfumu ya Sidon, ba-Ivi ya vandaka kuzinga na bangumba ya Liban, yantika ngumba Ba’al-Ermon tii kuna ndimba ya Amat.

Juges 3:26 [Interruption dans la versification après le verset 24] Ntangu ya bo vandaka kuvingila, Eyud vandaka me tina. Yandi lutaka “Biteke”, yandi bumbanaka na mbanza A-Seira.

Juges 5:31 [Il n'y a pas suffisamment de verset dans le chapitre] E Mfumu Nzambi, bika bambeni na nge kufwa, bo yonso mutindu yai ! Ye bayina ke zolaka nge, bo kuvanda bonso ntangu kwa yo ke basika na ngolo yonso ! Ibuna ntoto ya Israel kumaka na ngemba bamvula makumi iya.

1 Samuel 11:9 [Interruption dans la versification après le verset 7] Bo tubilaka bangenzi ya katukaka na Yabes nde : « Beno ta tuba mpila yai na bantu ya Yabes na ntoto ya Gala’ad : mbasi, kwa ntangu ta vanda makasi, bantu ta kwisa kusadisa beno. » Bangenzi vutukaka ; bo zabisaka bantu ya Yabes. Bo yonso monaka kiese.

1 Samuel 21:14 [Interruption dans la versification après le verset 12] Ibuna David kusaka diboma/kilau na meso na bo ti kusonika-sonika bidimbu na mabaya ya kielo, ye mate vandaka kubasika na munoko ti kukulumuka na mandefo na yandi .

2 Samuel 7:4 [Interruption dans la versification après le verset 2] Kansi na mpimpa yina, Mfumu Nzambi tindaka ndinga na yandi na Natan nde:  -

2 Samuel 13:13 [Interruption dans la versification après le verset 11] Mono ta kwenda wapi na nsoni yai ? Nge kibeni, nge ta kuma zoba ya nene mpenza na meso ya bantu yonso ya Israel ! Ntangu yai, mbote nge songa yo na ntotila, yandi ta buya ve na kukwedisa mono na nge*.

2 Samuel 24:13 [Interruption dans la versification après le verset 11] Ibuna Gad kwendaka kutubila David mambu yai ya Mfumu Nzambi tubaka nde :”Keti nge zola bamvula nsambwadi ya nzala na kati ya nsi na nge to bangonda tatu ya nge ta vanda kutina na ntwala ya bambeni ta kwisa kunwanisa nge bitumba, to bilumbu tatu ya kimbefo ya nsambukila ti ya lufwa? Nge yindula ntangu yai ye nge songa mono nki mvutu mono ta kwenda pesa na Mfumu Nzambi ya tindaka mono !”

Matthieu 1:0 [Chapitre excédentaire ou mauvaise versification]

Matthieu 1:2 [Verset excédentaire ou mauvaise versification] Abraham butaka Izaak. Izaak butaka Yako­bo. Yakobo butaka Yuda ti ba­mpangi na yandi.

Matthieu 1:3 [Verset excédentaire ou mauvaise versification] Yu­da butaka Farès ti Zara ; mama na bo, Ta­mar. Farès butaka Esrom. Esrom butaka Aram.

Matthieu 1:4 [Verset excédentaire ou mauvaise versification] Aram butaka Aminadab. Aminadab butaka Naason. Naason butaka Salmon.

Matthieu 1:5 [Verset excédentaire ou mauvaise versification] Salmon butaka Booz ; mama ya Booz, Rahab. Booz butaka Obed ; mama ya Obed, Ruth. Obed butaka Yessé.

Matthieu 1:6 [Verset excédentaire ou mauvaise versification] Yessé butaka ntotila Davidi. Davidi butaka Salomon ; mama ya Salomon va­nda­ka ntete nkento ya Urie.

Matthieu 1:7 [Verset excédentaire ou mauvaise versification] Salomon butaka Ro­boam. Roboam butaka Abia. Abia butaka Asaf.

Éléments 1 - 25 de 7979 [suivant] [actions]

It seems that the Old Testament books behave quite well...but the New Testament books do not.

**Comment by LAfricain** [comment]
Hello Mathew,
I have a good new! I don't know exactly if you change something to the sources, but I update well the git repo, rerun compilation and now it seems to be ok!! Maybe I had still bad files in my folder, maybe my bad use of git doesn't update well the repo!
And all is in French!!!
Thanks to God and to you :)

**Comment by postiffm** [comment]
You are welcome. I'm glad that at long last, it works! I did some code changes to make it possible.
