### ISSUE TITLE
Feature request: Add close button to concordance tabs

### ISSUE THREAD

**Issue by LAfricain** [postiffm/bibledit-desktop#44]
Currently they is no cross to close the different tabs in the concordance windows, I could be nice to do it.

**Comment by postiffm** [comment]
Related: https://stackoverflow.com/questions/8850043/how-can-i-make-tabs-in-pygtk-closable

**Comment by postiffm** [comment]
Or, perhaps better, to save screen real-estate, make the tab title right-clickable, and have a close option in a pop-up menu there.
