### ISSUE TITLE
Conflict between Bibledit and Bibledit-Desktop shortcut on Windows

### ISSUE THREAD

**Issue by LAfricain** [postiffm/bibledit-desktop#68]
Please update the Bibledit name to Bibledit-Desktop on Windows, because if we install [Bibledit](https://github.com/bibledit/cloud) we have problem with shortcuts on Desktop. Installing Bibledit remove the current Bibledit-Desktop shortcut name also Bibledit.

**Comment by postiffm** [comment]
2fb52e8 fixes this. Next Windows release will reflect the change.
