### ISSUE TITLE
Chapter out of range error in 1 John EMT

### ISSUE THREAD

**Issue by postiffm** [postiffm/bibledit-desktop#74]
In the Analysis window, Greek and English tab, the EMT in 1 John is giving us Chapter out of range error messages.

**Comment by postiffm** [comment]
This is probably related to another error I just found: 2 John and 3 John give a similar message, but other times I have seen an "error opening file" error message.

**Comment by Pickle** [comment]
Matt,

there is a type in the file names for john 1-3. I checked each book and
those are the only wrong one.

-                              "Phm.txt", "Heb.txt", "Jam.txt", "1Pe.txt",
"2Pe.txt", "1Jn.txt",
-                              "2Jn.txt", "3Jn.txt", "Jud.txt", "Rev.txt" };
+                              "Phm.txt", "Heb.txt", "Jam.txt", "1Pe.txt",
"2Pe.txt", "1Jo.txt",
+                              "2Jo.txt", "3Jo.txt", "Jud.txt", "Rev.txt" };

**Comment by postiffm** [comment]
Thank you for the tip. This is fixed with commit b770ba2
